export enum AuthError {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_EMAIL = "INVALID_EMAIL",
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
  INVALID_USERNAME = "INVALID_USERNAME",
  INVALID_PASSWORD = "INVALID_PASSWORD",

  USER_NOT_FOUND = "USER_NOT_FOUND",
}
